---
title: "NJ mammal metabarcoding"
author: "Mike Allen"
date: "1/11/2022"
output: html_document
---

# Load libraries and data formatting


```{r}
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)
'%notin%' <- Negate('%in%')

m_raw <- 
  readxl::read_xlsx("data/Max_0.8_fullOTU_resultstable_final.xlsx")

m <- m_raw %>%
  select(species = Species, starts_with("sample")) %>%
  mutate(species2 = species,
         species = case_when(substr(species2, 1, 9) == 
                               "Sciurus c" ~ 
                               "Sciurus carolinensis",
                              substr(species2, 1, 9) == 
                               "Scuirus c" ~ 
                               "Sciurus carolinensis",
                              substr(species2, 1, 9) == 
                               "Scuirius " ~ 
                               "Sciurus carolinensis",
                              substr(species2, 1, 9) == 
                               "Sciurius " ~ 
                               "Sciurus carolinensis",
                             species2 == "Scuirus niger" ~
                               "Sciurus carolinensis",
                             TRUE ~ species2)) %>%
  filter(species %notin% c("Sus scrofa", "Canis lupus familiares",
                           "Bos taurus", "Sus scrofa:domesticus")) %>%
  select(-species2) %>%
  group_by(species) %>%
  summarize_all(sum) %>%
  arrange(species)
  
m_flip <- m %>%
  t() %>%
  as.data.frame()
m_flip$sample <- rownames(m_flip)

# create all the sample names
roller_samples1 <-
  lapply(1:3, function(x)
    paste0("sample:R0", 1:9, LETTERS[x]))
roller_samples2 <-
  lapply(1:3, function(x)
    paste0("sample:R", 10:21, LETTERS[x]))

r <- data.frame(sample = c(do.call(c, roller_samples1),
                    do.call(c, roller_samples2))) %>%
  arrange(sample) %>%
  left_join(m_flip[2:33,], by = "sample") %>%
  replace(is.na(.), 0) %>%
  mutate(tree = substr(sample, 8, 10),
         visit = substr(sample, 11, 11)) %>%
  select(tree, visit, 2:12, -sample)
colnames(r) <-
  c("tree", "visit", 
    gsub(m$species, pattern = " ", replacement = "_"))

# create array for multispecies occupancy modelling
r_array <- array(0, dim = c(21, 3, 11))
for(s in 1:11){
  for(t in 1:21){
    for(v in 1:3){
      r_array[t, v, s] <- 
        as.numeric(r[r$tree==unique(r$tree)[t] & r$visit==r$visit[v],
                                      colnames(r)[s+2]])
      }
  }
  }
  
r_detnon <- r_array
r_detnon[r_detnon>0] <- 1  


```
# simplest commmunity occ mod from Kery and Royle
11.6.1 Simplest community occupancy model: n-fold single species
        occupancy model with species treated as fixed effects
```{r}
# define y as the mammal data
y <- r_detnon

# define number of species
nspec = 11

# Get observed number of species per site
tmp <- apply(y, c(1,3), max, na.rm = TRUE)
tmp[tmp == "-Inf"] <- NA
sort(C <- apply(tmp, 1, sum))     # Compute and print sorted species counts

# Observed number of occupied sites
tmp <- apply(y, c(1,3), max, na.rm = TRUE)
# For the 'all NA' site, max returns -Inf with a warning
tmp[tmp == -Inf] <- NA         # Change -Inf to NA
sort(obs.occ <- apply(tmp, 2, sum, na.rm = TRUE))
names(obs.occ) <- colnames(r)[3:13]

# Collapse 3D detection/nondetection data to 2D detection frequencies
ysum <- apply(y, c(1,3), sum, na.rm = T) # Collapse to detection frequency

# Bundle and summarize data set
str( win.data <- list(ysum = ysum, M = nrow(ysum), J = rep(3,21), nspec = dim(ysum)[2]) )

# Specify model in BUGS language
sink("model5.txt")
cat("
model {

# Priors
for(k in 1:nspec){          # Loop over species
   psi[k] ~ dunif(0, 1)
   p[k] ~ dunif(0, 1)
}

# Ecological model for latent occurrence z (process model)
for(k in 1:nspec){          # Loop over species
   for (i in 1:M) {         # Loop over sites
      z[i,k] ~ dbern(psi[k])
   }
}

# Observation model for observed data y
for(k in 1:nspec){          # Loop over species
   for (i in 1:M) {
      mup[i,k] <- z[i,k] * p[k]
      ysum[i,k] ~ dbin(mup[i,k], J[i])
   }
}

# Derived quantities
for(k in 1:nspec){          # Loop over species
   Nocc.fs[k] <- sum(z[,k]) # Add up number of occupied sites among the 267
}
for (i in 1:M) {            # Loop over sites
   Nsite[i] <- sum(z[i,])   # Add up number of occurring species at each site
}
}
",fill = TRUE)
sink()

# Initial values
zst <- apply(y, c(1,3), max) # Observed occurrence as inits for z
zst[is.na(zst)] <- 1
inits <- function() list(z = zst, psi = rep(0.4, nspec), p = rep(0.4, nspec))

# Parameters monitored
params <- c("psi", "p", "Nsite", "Nocc.fs")

# MCMC settings
ni <- 2500   ;   nt <- 2   ;   nb <- 500   ;   nc <- 3

# Call JAGS from R (ART 2.1 min)
out5 <- jags(win.data, inits, params, "model5.txt", n.chains = nc, n.thin = nt, n.iter = ni, n.burnin = nb, parallel = F)
par(mfrow = c(4,4))   ;   traceplot(out5)   ;   print(out5, dig = 3)

# Compare observed and estimated site species richness
par(cex = 1.3)
twice <- which(MHB2014$sites$nsurvey == 2)
dev.new()
plot(C, out5$summary[23:43,1], xlab = "Observed number of species", ylab = "Estimated number of species", frame = F, xlim = c(0, 10), ylim = c(0, 10), col = "red", pch = 16)
segments(C, out5$summary[23:43,3], C, out5$summary[23:43,7], col = "red")
abline(0,1)

# Observed and estimated number of occupied sites for each species
# in a table
cbind(obs.occu = obs.occ, out5$summary[44:54, c(1,3,7)])

# and in a plot
dev.new()
plot(obs.occ, out5$summary[44:54, 1], xlab = "Observed number of occupied sites", ylab = "Estimated version of quantity", ylim = c(0, 30), xlim = c(0,9), frame = F, pch = 16)
abline(0,1)
segments(obs.occ, out5$summary[44:54,3], obs.occ, out5$summary[44:54,7], col = "grey", lwd = 2)


# Estimated occupancy and detection probability for each species
plot(out5$summary[1:145,1], out5$summary[146:290,1], xlab = "Occupancy estimate", ylab = "Detection estimate", xlim = c(0,1), ylim = c(0,1), frame = F, pch = 16)
segments(out5$summary[1:145,3], out5$summary[146:290,1], out5$summary[1:145,7], out5$summary[146:290,1], col = "grey", lwd = 2)
segments(out5$summary[1:145,1], out5$summary[146:290,3], out5$summary[1:145,1], out5$summary[146:290,7], col = "grey", lwd = 2)


```
# More complex Community occupancy model from Kery and Royle
11.6.2 Community occupancy model with bivariate species-specific random effects
```{r}
# Bundle and summarize data set
str( win.data <- list(ysum = ysum, M = nrow(ysum), J = MHB2014$sites$nsurvey, nspec = dim(ysum)[2], R = matrix(c(5,0,0,1), ncol = 2), df = 3) )


# Specify model in BUGS language
sink("model6.txt")
cat("
model {

# Priors
for(k in 1:nspec){  # Group lpsi and lp together in array eta
   lpsi[k] <- eta[k,1]
   lp[k] <- eta[k,2]
   eta[k, 1:2] ~ dmnorm(mu.eta[], Omega[,])
}
# Hyperpriors
# Priors for mu.lpsi=mu.eta[1] and mu.lp=mu.eta[2]
# probs = community means of occupancy and detection probability
for(v in 1:2){
   mu.eta[v] <- log(probs[v] / (1-probs[v]))
   probs[v] ~ dunif(0,1)
}
# Prior for variance-covariance matrix
Omega[1:2, 1:2] ~ dwish(R[,], df)
Sigma[1:2, 1:2] <- inverse(Omega[,])

# Ecological model for latent occurrence z (process model)
for(k in 1:nspec){
   logit(psi[k]) <- lpsi[k]   # Must take outside of i loop
   for (i in 1:M) {
      z[i,k] ~ dbern(psi[k])
   }
}

# Observation model for observed data y
for(k in 1:nspec){
   logit(p[k]) <- lp[k]       # Needs to be outside of i loop
   for (i in 1:M) {
      mu.p[i,k] <- z[i,k] * p[k]
      ysum[i,k] ~ dbin(mu.p[i,k], J[i])
   }
}

# Derived quantities
rho <- Sigma[1,2] / sqrt(Sigma[1,1] * Sigma[2,2])  # Correlation coefficient
for(k in 1:nspec){
   Nocc.fs[k] <- sum(z[,k])   # Number of occupied sites among the 267
}
for (i in 1:M) {
   Nsite[i] <- sum(z[i,])     # Number of occurring species
}
}
",fill = TRUE)
sink()


# Initial values
zst <- apply(y, c(1,3), max) # Observed occurrence as starting values for z
zst[is.na(zst)] <- 1
inits <- function() list(z = zst, Omega = matrix(c(1,0,0,1), ncol = 2), eta = matrix(0, nrow = nspec, ncol = 2))

# Parameters monitored
params <- c("mu.eta", "probs", "psi", "p", "Nsite", "Nocc.fs", "Sigma", "rho")

# MCMC settings
ni <- 20000   ;   nt <- 15   ;   nb <- 5000   ;   nc <- 3

# Call JAGS from R (ART 12 min), check traceplots and summarize posteriors
out6 <- jags(win.data, inits, params, "model6.txt", n.chains = nc, n.thin = nt, n.iter = ni, n.burnin = nb, parallel = TRUE)
par(mfrow = c(3,3))   ;   traceplot(out6, c('mu.eta', 'probs', 'Sigma', 'rho'))
print(out6, 3)

# Graphically compare some estimates between fixed- and random-effects model
par(mfrow = c(2,2))      # not shown
# Species-specific occupancy (probability scale)
plot(out5$summary[1:11,1], out6$summary[5:15,1], main = "Species-specific occupancy probability")   ;   abline(0,1)
# Species-specific detection (probability scale)
plot(out5$summary[12:22,1], out6$summary[16:26,1], main = "Species-specific detection probability")   ;   abline(0,1)
# Site-specific species richness
plot(out5$summary[291:557,1], out6$summary[295:561,1], main = "Site-specific species richness (conditional on list of 145 detected)")   ;   abline(0,1)
# Species-specific number of presences
plot(out5$summary[558:702,1], out6$summary[562:706,1], main = "Species-specific number of presences (in 267 sites)")   ;   abline(0,1)

# Estimated occupancy and detection probability for each species
plot(out6$summary[5:15,1], out6$summary[16:26,1], xlab = "Occupancy estimate", ylab = "Detection estimate", xlim = c(0,1), ylim = c(0,1), frame = F, pch = 16)
segments(out6$summary[5:15,3], out6$summary[16:26,1], out6$summary[5:15,7], out6$summary[16:26,1], col = "grey", lwd = 2)
segments(out6$summary[5:15,1], out6$summary[16:26,3], out6$summary[5:15,1], out6$summary[16:26,7], col = "grey", lwd = 2)
points(out6$summary[5:15,1], out6$summary[16:26,1], xlab = "Occupancy estimate", ylab = "Detection estimate", xlim = c(0,1), ylim = c(0,1), frame = F, pch = 16)

detprob <- as.data.frame(out6$summary[16:26,]) %>%
  rename(q2.5 = 3, q97.5 = 7) %>%
  mutate(species = names(obs.occ))

occprob <- as.data.frame(out6$summary[5:15,]) %>%
  rename(q2.5 = 3, q97.5 = 7) %>%
  mutate(species = names(obs.occ))

detprob_tree <- detprob[c(1,2,6:8),]

occprob_tree <- occprob[c(1,2,6:8),]


ggplot(detprob_tree) +
  geom_errorbar(aes(xmin = q2.5, xmax = q97.5, y = species), width = 0) +
  geom_point(aes(x = mean, y = species), size = 2, color = "firebrick") +
  theme(text = element_text(size = 4)) +
  theme_bw() +
  labs(y = "", x = "Detection probability") +
  scale_x_continuous(limits = c(0,1))
  
ggsave("figures/detprob_tree.png", height = 1000, width = 2000, units = "px", dpi = 600)

ggplot(occprob_tree) +
  geom_errorbar(aes(xmin = q2.5, xmax = q97.5, y = species), width = 0) +
  geom_point(aes(x = mean, y = species), size = 2, color = "steelblue") +
  theme(axis.text = element_text(size = 4)) +
  theme_bw() +
  labs(y = "", x = "Occupancy probability") +
  scale_x_continuous(limits = c(0,1))
  
ggsave("figures/occprob_tree.png", height = 1000, width = 2000, units = "px", dpi = 600)

```


