---
title: "NJ mammal metabarcoding"
author: "Mike Allen"
date: "1/11/2022"
output: html_document
---

# Load libraries and data formatting


```{r}
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)
'%notin%' <- Negate('%in%')

# read in raw read data
m_raw <- 
  readxl::read_xlsx("data/resultstable_justvert_probcon.xlsx")

# clean version summarized by OTU
m_all <- m_raw %>%
  select(species = Species, group = Group, 
         starts_with("R"), starts_with("S")) %>%
  mutate(species2 = species,
         species = case_when(group == 
                               "Squirrel" ~ 
                               "Sciurus carolinensis",
                             TRUE ~ species2)) %>%
  filter(group %notin% c("Pig", "Cow")) %>%
  select(-species2, -group) %>%
  arrange(species)

# clean version summarized by species
m_sum <- m_all %>%
  group_by(species) %>%
  summarize_all(sum) %>%
  arrange(species)
  
m_flip <- m_sum %>%
  t() %>%
  as.data.frame()
m_flip$sample <- rownames(m_flip)

# create all the sample names
roller_samples1 <-
  lapply(1:3, function(x)
    paste0("R0", 1:9, LETTERS[x]))
roller_samples2 <-
  lapply(1:3, function(x)
    paste0("R", 10:21, LETTERS[x]))
soil_samples1 <-
  lapply(1:3, function(x)
    paste0("S0", 1:9, LETTERS[x]))
soil_samples2 <-
  lapply(1:3, function(x)
    paste0("S", 10:21, LETTERS[x]))

m_sum_full <- data.frame(sample = c(do.call(c, roller_samples1),
                    do.call(c, roller_samples2),
                    do.call(c, soil_samples1),
                    do.call(c, soil_samples2))) %>%
  arrange(sample) %>%
  left_join(m_flip, by = "sample") %>%
  replace(is.na(.), 0) %>%
  mutate(tree = paste0("T", substr(sample, 2, 3)),
         visit = substr(sample, 4, 5),
         method = substr(sample, 1, 1),
         site = substr(sample, 1, 3)) %>%
  select(tree, visit, method, site, 2:19)
colnames(m_sum_full) <-
  c("tree", "visit", "method", "site",
    gsub(gsub(m_sum$species, pattern = " ", replacement = "_"),
         pattern = ",", replacement = ""))

tmp <- matrix(as.numeric(as.matrix(m_sum_full[,5:22])), 
                   nrow = 126, ncol = 18,
                    byrow = F) %>%
  as.data.frame()
colnames(tmp) <- colnames(m_sum_full[,5:22])

m_sum_full <- cbind.data.frame(m_sum_full[,1:4], tmp)

# define variables
n_trees <- 21
n_sites <- 42 # num unique sampling locations
n_species <- 18
n_visits <- 3
n_methods <- 2

# create array for multispecies occupancy modelling
m_sum_array <- array(0, dim = c(n_sites, n_visits, n_species))
for(s in 1:n_species){
  for(t in 1:n_sites){
    for(v in 1:n_visits){
      m_sum_array[t, v, s] <- 
        m_sum_full[m_sum_full$site==unique(m_sum_full$site)[t] &
                     m_sum_full$visit==m_sum_full$visit[v],
                                      colnames(m_sum_full)[s+4]]
      }
  }
  }
  
m_sum_detnon <- m_sum_array
m_sum_detnon[m_sum_detnon>0] <- 1  

# create matrix for NMDS
m_sum_mat <- as.matrix(tmp)

rm(tmp, roller_samples1, roller_samples2, soil_samples1, soil_samples2)
 

# format for occupancy

# define y as the mammal data
y_roll <- m_sum_detnon[1:21,,]
y_soil <- m_sum_detnon[22:42,,]

# define number of species
nspec = n_species

# Get observed number of roller-identified species per site
tmp <- apply(y_roll, c(1,3), max, na.rm = TRUE)
tmp[tmp == "-Inf"] <- NA
sort(C_roll <- apply(tmp, 1, sum))     # Compute and print sorted species counts

# Get observed number of soil-identified species per site
tmp <- apply(y_soil, c(1,3), max, na.rm = TRUE)
tmp[tmp == "-Inf"] <- NA
sort(C_soil <- apply(tmp, 1, sum))     # Compute and print sorted species counts

# Observed number of occupied sites per species (roller)
tmp <- apply(y_roll, c(1,3), max, na.rm = TRUE)
# For the 'all NA' site, max returns -Inf with a warning
tmp[tmp == -Inf] <- NA         # Change -Inf to NA
sort(obs.occ_roll <- apply(tmp, 2, sum, na.rm = TRUE))
names(obs.occ_roll) <- colnames(m_sum_full)[5:(n_species+4)]

# Observed number of occupied sites per species (soil)
tmp <- apply(y_soil, c(1,3), max, na.rm = TRUE)
# For the 'all NA' site, max returns -Inf with a warning
tmp[tmp == -Inf] <- NA         # Change -Inf to NA
sort(obs.occ_soil <- apply(tmp, 2, sum, na.rm = TRUE))
names(obs.occ_soil) <- colnames(m_sum_full)[5:(n_species+4)]

# Collapse 3D detection/nondetection data to 2D detection frequencies
ysum_roll <- apply(y_roll, c(1,3), sum, na.rm = T) 
ysum_soil <- apply(y_soil, c(1,3), sum, na.rm = T) 

```

# Roller Community occupancy model
From Kery and Royle 11.6.2 Community occupancy model with bivariate species-specific random effects
```{r}
# Bundle and summarize data set
str( win.data <- list(ysum = ysum_roll, M = nrow(ysum_roll), J = rep(3, 21), nspec = dim(ysum_roll)[2], R = matrix(c(5,0,0,1), ncol = 2), df = 3) )


# Specify model in BUGS language
sink("model6.txt")
cat("
model {

# Priors
for(k in 1:nspec){  # Group lpsi and lp together in array eta
   lpsi[k] <- eta[k,1]
   lp[k] <- eta[k,2]
   eta[k, 1:2] ~ dmnorm(mu.eta[], Omega[,])
}
# Hyperpriors
# Priors for mu.lpsi=mu.eta[1] and mu.lp=mu.eta[2]
# probs = community means of occupancy and detection probability
for(v in 1:2){
   mu.eta[v] <- log(probs[v] / (1-probs[v]))
   probs[v] ~ dunif(0,1)
}
# Prior for variance-covariance matrix
Omega[1:2, 1:2] ~ dwish(R[,], df)
Sigma[1:2, 1:2] <- inverse(Omega[,])

# Ecological model for latent occurrence z (process model)
for(k in 1:nspec){
   logit(psi[k]) <- lpsi[k]   # Must take outside of i loop
   for (i in 1:M) {
      z[i,k] ~ dbern(psi[k])
   }
}

# Observation model for observed data y
for(k in 1:nspec){
   logit(p[k]) <- lp[k]       # Needs to be outside of i loop
   for (i in 1:M) {
      mu.p[i,k] <- z[i,k] * p[k]
      ysum[i,k] ~ dbin(mu.p[i,k], J[i])
   }
}

# Derived quantities
rho <- Sigma[1,2] / sqrt(Sigma[1,1] * Sigma[2,2])  # Correlation coefficient
for(k in 1:nspec){
   Nocc.fs[k] <- sum(z[,k])   # Number of occupied sites among the 267
}
for (i in 1:M) {
   Nsite[i] <- sum(z[i,])     # Number of occurring species
}
}
",fill = TRUE)
sink()


# Initial values
zst <- apply(y_roll, c(1,3), max) # Observed occurrence as starting values for z
zst[is.na(zst)] <- 1
inits <- function() list(z = zst, Omega = matrix(c(1,0,0,1), ncol = 2), eta = matrix(0, nrow = nspec, ncol = 2))

# Parameters monitored
params <- c("mu.eta", "probs", "psi", "p", "Nsite", "Nocc.fs", "Sigma", "rho")

# MCMC settings
ni <- 20000   ;   nt <- 15   ;   nb <- 5000   ;   nc <- 3

# Call JAGS from R (ART 12 min), check traceplots and summarize posteriors
out6 <- jagsUI::jags(win.data, inits, params, "scripts/model6.txt", n.chains = nc, n.thin = nt, n.iter = ni, n.burnin = nb, parallel = TRUE)
par(mfrow = c(3,3))   ;   jagsUI::traceplot(out6, c('mu.eta', 'probs', 'Sigma', 'rho'))
print(out6, 3)


detprob_roll <- as.data.frame(out6$summary[23:40,]) %>%
  rename(q2.5 = 3, q97.5 = 7, q25 = 4, q75 = 6) %>%
  mutate(species = names(obs.occ_roll),
         obs.occ = obs.occ_roll) %>%
  mutate(species = forcats::fct_reorder(species, mean, .desc = F))

occprob_roll <- as.data.frame(out6$summary[5:22,]) %>%
  rename(q2.5 = 3, q97.5 = 7, q25 = 4, q75 = 6) %>%
  mutate(species = names(obs.occ_roll),
         obs.occ = obs.occ_roll,
         naive.occ = obs.occ_roll/n_trees) %>%
  mutate(species = forcats::fct_reorder(species, mean, .desc = F))


ggplot(detprob_roll) +
  geom_errorbar(aes(xmin = q2.5, xmax = q97.5, y = species), 
                width = 0, color = "firebrick") +
  geom_errorbar(aes(xmin = q25, xmax = q75, y = species), 
                size = 1.5, width = 0, color = "firebrick") +
  geom_point(aes(x = mean, y = species), size = 3, color = "firebrick") +
  theme(text = element_text(size = 4)) +
  theme_bw() +
  labs(y = "", x = "Detection probability") +
  scale_x_continuous(limits = c(0,1))
  
ggsave("figures/detprob_roll.png", height = 6, width = 7, dpi = 400)

ggplot(occprob_roll) +
  geom_errorbar(aes(xmin = q2.5, xmax = q97.5, y = species), 
                width = 0, color = "steelblue") +
  geom_errorbar(aes(xmin = q25, xmax = q75, y = species), 
                width = 0, size = 1.5, color = "steelblue") +
  geom_point(aes(x = mean, y = species), size = 2, color = "steelblue") +
  theme(axis.text = element_text(size = 4)) +
  theme_bw() +
  labs(y = "", x = "Occupancy probability") +
  scale_x_continuous(limits = c(0,1))
  
ggsave("figures/occprob_roll.png", height = 6, width = 7, dpi = 400)

```

# Mammals
used this site for code:
https://rstudio-pubs-static.s3.amazonaws.com/694016_e2d53d65858d4a1985616fa3855d237f.html
```{r}
library(vegan)
library(BiodiversityR)

r_detnon_mat <- r_mat
r_detnon_mat[r_detnon_mat>0] <- 1
r_mat_mean <- 
  aggregate(r_mat, by = list(r$tree), mean) %>%
  select(-Group.1) %>%
  as.matrix()

r_mat_mean_no_blanks <- r_mat_mean[which(rowSums(r_mat_mean)>0),]

env.data <- data.frame(
tree_name = unique(r$tree)[which(rowSums(r_mat_mean)>0)]
)

mammal_NMDS=metaMDS(r_mat_mean_no_blanks, # Our community-by-species matrix
                     k=2, distance = 'bray', trymax = 100) # The number of reduced dimensions. Increase if high stress is problem. 

plot1 <- ordiplot(mammal_NMDS, choices = c(1, 2))

sites.long1 <-
  BiodiversityR::sites.long(plot1, env.data = env.data) %>%
  mutate(axis1 = as.numeric(axis1),
         axis2 = as.numeric(axis2))
head(sites.long1)
str(sites.long1)

ggplot(sites.long1) +
  geom_vline(xintercept = c(0),
             color = "grey70",
             linetype = 2) +
  geom_hline(yintercept = c(0),
             color = "grey70",
             linetype = 2) +     
  xlab("NMDS1") +
  ylab("NMDS2") +
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  geom_text(aes(
    x = axis1,
    y = axis2,
    label = tree_name
  ),
  size = 5) +
  #BioR.theme +
  ggsci::scale_colour_npg() +
  coord_fixed(ratio = 1)


```


